### PR TITLE
Some display fixes

### LINKED ISSUE #28: Create 'SubjectivityScore' Component
Gauge to display:
- [ ] Subjectivity Score returned from backend.
- [ ] Some explanation text

**A note that subjectivity goes from 0 to 1 (with '0' being neutral/good).**

Response object will look like:
```
{
  'url':'http://bbc.co.uk',
  'article' : {
    'header' : 'An Article Title',
    'summary' : 'The Article Summary',
    'keywords' : ['Boris Johnson', 'Brexit']
  },
  'results' : [
    { 'type' : 'credibility' ...... },
    { 'type' : 'polarity' ..... },
    { 'type' : 'subjectivity' .....},
    { 'type' : 'biasscore' .....}
  ]
}
```

### PR DESCRIPTION
**Pull request by abirdonwire**
- Fix the credibility score so it displays correct percentage
- add Key props to keyword Chips so they are properly handled
- Remove Chips from being nested within a Typography component

### CODE REVIEW

File: src/components/Results/Credibility.js [hunk 1]
```diff
@@ -56,6 +56,22 @@ const useStyles = makeStyles({
 
 function Credibility(props) {
   const classes = useStyles();
+  let score;
+  let category;
+  let source;
+
+  const handleError = () =>{
+    if (isNaN(props.score)){
```
Comment (jsjohnstone) [inline src/components/Results/Credibility.js]: I think @ANA-POTJE could chime in here on how errors are 'created'?

I think the best way to detect an error is to test if results[0].outcome.error is defined - if it is, it means an error occurred... otherwise outcome.score, outcome.category etc should all be set.

File: src/components/Results/displayResults.js [hunk 2]
```diff
@@ -9,27 +9,21 @@ function DisplayResults(props) {
...
 
-
-  // temporary code to support credibility score while it's here
   const credibilityScore = resultsObj.results[0].outcome.score / 100;
   const source = resultsObj.results[0].outcome.source;
   const category = resultsObj.results[0].outcome.category;
 
   return (
     <div>
+      <ArticleSummary displayURL={analysedURL} displayArticle={article} />
```
Comment (jsjohnstone) [inline src/components/Results/displayResults.js]: In relation to the note above, I wonder if passing the entire results object would be more useful in detecting an error:

`<Credibility outcome={resultsObj.results[0].outcome}>
`
I think this works fine in the meantime though.

**Review by jsjohnstone — COMMENTED** [review]
Just a comment about error handling/props in the credibility component.

File: src/components/Results/Credibility.js (hunk 1 above)
Comment (ANA-POTJE) [reply src/components/Results/Credibility.js]: If the news website has no rating (nothing is returned from the Gate Source API), then we will get the following message from lambda: "error" : "The credibility score was not available."
E.g. please check the URL = https://socialistworker.co.uk/

Comment (abirdonwire) [reply src/components/Results/Credibility.js]: I will have a look, thanks guys.

File: src/components/Results/displayResults.js (hunk 2 above)
Comment (abirdonwire) [reply src/components/Results/displayResults.js]: This is better! I'll go see what I can do.
